# Site
repository: bcchoi0202/r
favicon: images/favicon.ico

version: 2

# Personal info
name: 최병철
title: Android Developer
email: bcchoi0202@gmail.com
phone: 010-6411-8658
website: https://github.com/bcchoi0202

# Social links
#twitter_username: sproogen
github_username:  bcchoi8658
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: byungchul0202
#linkedin_username: jameswgrant
# pinterest_username:
# youtube_username:

#About Section
about_title: About me
about_profile_image: images/me.jpg
about_content: |
  <span style="display: inline-block; width: 95%; text-align: right;"> [![Hits](https://hits.sh/github.com/bcchoi0202/hits.svg)](https://hits.sh/github.com/silentsoft/hits/)</span>  
  **저는 이런 개발자입니다.**
  - 빠르고 사용하기 쉬우면서도 사용에 즐거움을 더해주는 경험을 제공하는 것을 좋아하는  
  - 사용자 관점을 최우선으로 생각하고 고민하는
  - 새로운 기술을 배우고 검토 및 도입하는
  - 재미와 건강, 함께 하는(할 수 있는) 것에 관심이 많은
  - "함께"의 재미를 알고 소통을 즐길 줄 아는

  **저는 이런 근무 환경을 선호합니다.**
  - 출근과 퇴근시간을 본인이 결정할 수 있는
  - 의사결정이 투명하게 이뤄지고 관련 정보의 공유가 수평적인
  - 더욱 건강한 개발문화를 함께 만들어 가는    

content:
  - title: Skill-Stack
    layout: text
    content: |
      |<font size="4">Category</font>|<font size="4">Skills</font>|
      |<font size="3">Language</font>|<mark>Java</mark> <mark>Kotlin</mark>  |
      |<font size="3">Architecture</font>|<mark>MVC</mark> <mark>MVP</mark> <mark>MVVM</mark> <mark>MVI(~ing)</mark>|
      |<font size="3">Stream</font>|<mark>rxJava</mark> <mark>rxKotlin</mark> <mark>rxAndroid</mark> <mark>Livedata</mark> <mark>Coroutine</mark>|
      |<font size="3">Network</font>|<mark>Retrofit</mark> <mark>OkHttp</mark>|
      |<font size="3">Libraries</font>|<mark>Navigation</mark> <mark>Pager</mark> <mark>ViewModel</mark> <mark>DataBinding</mark> <mark>Jetpack Compose</mark> <mark>Glide</mark> <mark>Coil</mark>|
      |<font size="3">Database</font>|<mark>Room</mark> <mark>Realm</mark>|
      |<font size="3">DI</font>|<mark>Koin</mark> <mark>Hilt</mark>|
      |<font size="3">Testing</font>|<mark>Junit</mark> <mark>Espresso</mark> <mark>Mockito</mark>|
      |<font size="3">Design</font>|<mark>Zeplin</mark> <mark>Figma</mark>|
      |<font size="3">VCS</font>|<mark>Svn</mark> <mark>Git</mark>|
      |<font size="3">Communication</font>|<mark>Jira</mark> <mark>Slack</mark>|
      |<font size="3">Management</font>|<mark>Analytics</mark> <mark>Crashlytics</mark> <mark>AppsFlyer</mark>|    
      |<font size="3">To-Do</font>|<mark>Clean architecture</mark> <mark>Jetpack Compose</mark> <mark>TDD</mark>|  

  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Danal
        sub_title: Android Developer
        link: https://www.danal.co.kr/
        caption: 2022.03 ~ 현재
        description: |
          * 다날 다모음 Android App 개발
          * 포인트 충전 시스템 개발
          * 실물 카드 관리 서비스 개발
          * 레거시코드 제거 및 최적화로 가독성 및 개발속도 향상
          * 모듈 분리를 통한 빌드속도 n% 감소 및 유지보수성 향상
            * Single module -> Multi module Migration
            * Clean Architecture / Repository pattern Migration
          * Refactoring을 통한 Boiler plate code 제거 및 성능 향상  
            * rxJava, LiveData -> Coroutine, Flow Migration
            * Kotlin DSL 적용
            * Koin -> Hilt Migration
            * Compose Migration  
          
          <mark>Kotlin</mark> <mark>Kotlin DSL</mark> <mark>Retrofit</mark> <mark>Glide</mark> <mark>rxJava</mark> <mark>LiveData</mark> <mark>View/DataBinding</mark> <mark>Jetpack AAC</mark> <mark>Jetpack Compose</mark> <mark>Hilt</mark> <mark>MVVM</mark> <mark>Firebase</mark> <mark>AppsFlyer</mark>
      - layout: left
        border: weak
        title: Rainus
        link: https://www.rainusbiz.com/ko/
        sub_title: Android Developer
        caption: 2021.07 ~ 2022.02
        description: |
          * Rainus Player 내 상품 가격태그 표시 기능 개발
            * 가격태그 관련 rating, reviews, advertise 등 컨텐츠 추가 및 제어
          
          <mark>Kotlin</mark> <mark>Retrofit</mark> <mark>Glide</mark> <mark>rxJava</mark> <mark>LiveData</mark> <mark>View/DataBinding</mark> <mark>Koin</mark> <mark>MVVM</mark>

      - layout: left
        border: weak
        title: Bixolon
        sub_title: Android Developer
        link: https://www.bixolon.com/
        caption: 2018.03 ~ 2021.03
        description: |
          * Bixolon Label Printer Android SDK 개발 및 유지보수
            * 코어 모듈 리팩토링을 통해 인쇄 및 프린터 설정 기능 개선
          * Mobile printer용 결제 App 3사(KICC, NICE, KS-NET) 통합
            * One Source 관리를 통한 유지보수성 향상 
          * Bixolon Printer Javascript SDK 개발
            * Web 환경에서의 프린터 접근성 향상
            * 마켓컬리 물류센터 내 해당 SDK 사용 및 납품 계약 체결 
          
          <mark>Java</mark> <mark>Kotlin</mark> <mark>Retrofit</mark> <mark>Glide</mark> <mark>MVC</mark> <mark>MVP</mark>

      - layout: left
        border: weak
        title: Zin Corp.
        sub_title: Android Development
        link: http://zin.co.kr/
        caption: 2014.01 ~ 2017.09
        description: |
          * SPC 그룹사 Mobile POS 및 점포 컨설팅 Android App 개발
            * 주문 내역 리스트 표시 속도 x% 개선
            * Logger 적용으로 디버그 용이성 증가
          * 파리크라상/파스쿠찌 점포 컨설팅 App 개발(관리자/슈퍼바이저 용)
            * Custom View 구현 및 적용으로 사용량 y% 증가
          
          <mark>Java</mark> <mark>log4j</mark> <mark>AChartEngine</mark> <mark>MVC</mark>

  - title: Education
    layout: list
    content:
      - layout: left
        title: 한신대학교
        sub_title: 컴퓨터 공학부
        caption: 2006.03 - 2014.02

      - layout: left
        title: 수원 동원고등학교
        sub_title: 이공계 졸업
        caption: 2003.03 - 2006.02


  - title: In ordinary days
    layout: text
    content: | 
      책상에 앉아서 공부하는 날 외에는 캠핑, 낚시, 당구, 스노우보드, 서핑 등 활동적인 컨텐츠를 즐깁니다. 새로운 무언가에 도전하는것을 좋아하여 여러 분야의 사람들과 함께 스포츠를 즐기고, 배우곤 합니다.  
      또한 사람들을 만나 맛있는 것을 먹고, 무언가를(?) 마시는 것도 좋아해서 여러가지 활동적인 모임을 좋아하기도 합니다.  
      평일에는 가급적 책상과 가까이 붙어 있으려 노력하고, Side Project 또는 학습중인 기술에 대한 프로토타입 등을 만드는 등 이해도를 높여가는 시간을 갖습니다.

  - title: Finally
    layout: text
    content: |
      다양한 프로젝트를 개발해오며 Android 개발자로서의 기술 스택 및 경험, 그리고 자질을 쌓아왔습니다. 지금도, 그리고 앞으로도 꾸준히 노력하겠습니다.  

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
