# Site
repository: bcchoi0202/r
favicon: images/favicon.ico

version: 2

# Personal info
name: 최병철
title: Android Developer
email: bcchoi0202@gmail.com
phone: 010-6411-8658

# Social links
#twitter_username: sproogen
github_username:  bcchoi8658
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: byungchul0202
#linkedin_username: jameswgrant
# pinterest_username:
# youtube_username:

#About Section
about_title: About me
about_profile_image: images/me.jpg
about_content: |
  **저는 이런 개발자입니다.**
  - 빠르고 사용하기 쉬우면서도 사용에 즐거움을 더해주는 경험을 제공하는 것을 좋아하는  
  - 사용자 관점을 최우선으로 생각하고 고민하는
  - 새로운 기술을 배우고 검토 및 도입하는
  - 재미와 건강, 함께 하는(할 수 있는) 것에 관심이 많은
  - "함께"의 재미를 알고 소통을 즐길 줄 아는

  **저는 이런 근무 환경을 선호합니다.**
  - 출근과 퇴근시간을 본인이 결정할 수 있는
  - 의사결정이 투명하게 이뤄지고 관련 정보의 공유가 수평적인
  - 더욱 건강한 개발문화를 함께 만들어 가는 

content:
  - title: Skill-Stack
    layout: list
    content:
      - layout: top-left
        sub_title: Language
        description: |
          <mark>Java</mark> <mark>Kotlin</mark>
      - layout: left
        sub_title: Architecture
        description: |
          <mark>MVC</mark> <mark>MVP</mark> <mark>MVVM</mark> <mark>MVI(~ing)</mark>
      - layout: top-start
        sub_title: Stream
        description: |
          <mark>rxJava</mark> <mark>rxKotlin</mark> <mark>rxAndroid</mark> <mark>Livedata</mark> <mark>Coroutine</mark>
      - layout: left
        sub_title: Network
        description: |
          <mark>Retrofit</mark> <mark>OkHttp</mark>
      - layout: top-left
        sub_title: Libraries
        description: |
          <mark>Navigation</mark> <mark>Pager</mark> <mark>ViewModel</mark> <mark>DataBinding</mark> <mark>Jetpack Compose</mark> <mark>Glide</mark> <mark>Coil</mark>
      - layout: left
        sub_title: Database
        description: |
          <mark>Room</mark> <mark>Realm</mark>
      - layout: left
        sub_title: DI
        description: |
          <mark>Koin</mark> <mark>Hilt</mark>
      - layout: left
        sub_title: Test
        description: |
          <mark>Junit</mark> <mark>Espresso</mark> <mark>Mockito</mark>
      - layout: left
        sub_title: Design
        description: |
          <mark>Zeplin</mark> <mark>Figma</mark>
      - layout: left
        sub_title: VCS
        description: |
          <mark>Svn</mark> <mark>Git</mark> <mark>Trello</mark>
      - layout: left
        sub_title: Communication
        description: |
          <mark>Jira</mark> <mark>Slack</mark>
      - layout: left
        sub_title: Management
        description: |
          <mark>Analytics</mark> <mark>Crashlytics</mark> <mark>AppsFlyer</mark>
  - title: 핵심 역량
    layout: text
    content:

  - title: Experience
    layout: list
    content:
      - layout: top-left
        border: weak
        title: (주)다날
        sub_title: Android Developer
        link: https://www.danal.co.kr/
        caption: 2022.03 ~ 현재
        description: |
          **담당업무**
          * 다모음 App 개발 및 유지보수
          * 다모음 포인트 충전 기능 개발 
          * 실물 카드 발급/재발급/등록/분실신고 등 실물 카드 관리 서비스 개발
          * 다모음 App 리팩토링
            * Single module -> Multi module Migration
            * Clean Architecture / Repository pattern Migration
            * rxJava, LiveData -> Coroutine, Flow Migration
            * Kotlin DSL 적용
            * Koin -> Hilt Migration
            * Compose Migration    
          
            <mark>Kotlin</mark> <mark>Kotlin DSL</mark> <mark>Retrofit</mark> <mark>Glide</mark> <mark>rxJava</mark> <mark>LiveData</mark> <mark>View/DataBinding</mark> <mark>Jetpack AAC</mark> <mark>Jetpack Compose</mark> <mark>Hilt</mark> <mark>MVVM</mark> <mark>Firebase</mark> <mark>AppsFlyer</mark>  
          
          **핵심 역량**
          > - 다모음 App 신규 Feature 개발/운영 및 개선
          > - 레거시 코드 제거 및 신규 기술 스택 도입
          > - 일 평균 DAU 4.8만 

      - layout: top
        border: weak
        title: Rainus
        link: https://www.rainusbiz.com/ko/
        sub_title: Android Developer
        caption: 2021.07 ~ 2022.02
        description: |
          * Signage 기기 제어용 Launcher App 개발
          * Signage 기기 광고 재생용 Player App 개발  
          
          **Used skill stack**  
            <mark>Kotlin</mark> <mark>Retrofit</mark> <mark>Glide</mark> <mark>rxJava</mark> <mark>LiveData</mark> <mark>View/DataBinding</mark> <mark>Koin</mark> <mark>MVVM</mark>
          
          > Rainus의 자체 Signage Device 용 Launcher 및 Player App 내 신규기능 개발 및 개선

      - layout: left-bottom
        border: weak
        title: (주)Bixolon
        sub_title: Android Developer
        link: https://www.bixolon.com/
        caption: 2018.03 ~ 2021.03
        description: |
          * Mobile printer용 결제 App 3사(KICC, NICE, KS-NET) 통합
          * McDonald's(미국), Lotte GRS 계열사 유통기한 라벨링 App 개발
          * 마켓컬리 주문 체크 라벨링 App 개발
          * 라벨 디자인 App 개발  
          
          **Used skill stack**  
            <mark>Java</mark> <mark>Kotlin</mark> <mark>Retrofit</mark> <mark>Glide</mark> <mark>MVVM</mark> <mark>MVP</mark>
          
          > Bixolon Label Printer와 관련된 전반적인 Application 개발/유지보수 및 개선
      - layout: left-top
        border: weak
        title: (주)진코퍼레이션
        sub_title: Android Development
        link: http://zin.co.kr/
        caption: 2014.01 ~ 2017.09
        description: |
          * 파리바게트/파리크라상 점포 컨설팅 App 개발(관리자/슈퍼바이저 용)
          * 국내 파리크라상 계열 브랜드용 Mobild POS App 개발 (점주/매니저 용)
          * 중국 Tamati Mobile Order App 개발(홀 - 주방 프린터 연동)  
          
          **Used skill stack**  
            <mark>Java</mark> <mark>log4j</mark> <mark>AChartEngine</mark> <mark>MVC</mark>
          
          > SPC 계열사의 Mobile POS 및 주문 시스템 개발 및 유지보수

  - title: Education
    layout: list
    content:
      - title: 한신대학교
        sub_title: 컴퓨터 공학부
        caption: 2006.03 - 2014.02

      - title: 수원 동원고등학교
        sub_title: 이공계 졸업
        caption: 2003.03 - 2006.02

  - title: In ordinary days
    layout: text
    content: | 
      책상에 앉아서 공부하는 날 외에는 캠핑, 낚시, 당구, 스노우보드, 서핑 등 활동적인 컨텐츠를 즐깁니다. 새로운 무언가에 도전하는것을 좋아하여 여러 분야의 사람들과 함께 스포츠를 즐기고, 배우곤 합니다.  
      또한 사람들을 만나고, 맛있는 것을 먹고, 무언가를(?) 마시는 것도 좋아해서 여러가지 활동적인 모임을 좋아하기도 합니다.  
      평일에는 가급적 책상과 가까이 붙어 있으려 노력하고, Side Project 또는 학습중인 기술에 대한 프로토타입 등을 만드는 등 이해도를 높여가는 시간을 갖습니다.

  - title: Finally
    layout: text
    content: |
      다양한 프로젝트를 개발해오며 Android 개발자로서의 기술 스택 및 경험, 그리고 자질을 쌓아왔습니다. 지금도, 그리고 앞으로도 꾸준히 노력하겠습니다.
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
