# Site
repository: bcchoi0202/r
favicon: images/favicon.ico

version: 2

# Personal info
name: 최병철 이력서
title: Android Developer
email: bcchoi0202@gmail.com
phone: 010-6411-8658

# Social links
#twitter_username: sproogen
github_username:  bcchoi8658
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: byungchul0202
#linkedin_username: jameswgrant
# pinterest_username:
# youtube_username:

#About Section
about_title: About me
about_profile_image: images/me2.jpeg
about_content: |
  <span style="display: inline-block; width: 95%; text-align: right;"> [![Hits](https://hits.sh/github.com/bcchoi0202/hits.svg)](https://hits.sh/github.com/silentsoft/hits/)</span>  
  **저는 __________ 개발자입니다.**
  - 쉽고 빠른 경험을 제공하는 것을 좋아하는  
  - 사용자 관점을 최우선으로 생각하고 고민하는
  - 끊임 없이 기존 코드를 분석하고 개선하는
  - 새로운 기술을 배우고 검토 및 도입하는
  - 재미와 건강, 함께 하는(할 수 있는) 것에 관심이 많은
  - "함께"의 재미를 알고 소통을 즐길 줄 아는
  - 건강한 개발 문화를 함께 만들어 가는
  <br>
#  **저는 이런 근무 환경을 선호합니다.**
#  - 출근과 퇴근시간을 본인이 결정할 수 있는
#  - 의사결정이 투명하게 이뤄지고 관련 정보의 공유가 수평적인
#  - 더욱 건강한 개발문화를 함께 만들어 가는
content:
  - title: Skill-Stack
    layout: text
    content: | 
      아래는 현재 사용하고 있거나, 기존 프로젝트에서 자주 사용했던 기술 스택입니다.
      <br>  
      
      |<font size="3">Language</font>|<mark><font size="2">Java</font></mark> <mark><font size="2">Kotlin</font></mark>|
      |<font size="3">Architecture</font>|<mark><font size="2">MVC</font></mark> <mark><font size="2">MVP</font></mark> <mark><font size="2">MVVM</font></mark> <mark><font size="2">MVI(~ing)</font></mark>|
      |<font size="3">Stream</font>|<mark><font size="2">rxJava</font></mark> <mark><font size="2">rxKotlin</font></mark> <mark><font size="2">rxAndroid</font></mark> <mark><font size="2">Livedata</font></mark> <mark><font size="2">Coroutine</font></mark> <mark><font size="2">Flow</font></mark>|
      |<font size="3">Network</font>|<mark><font size="2">Retrofit</font></mark> <mark><font size="2">OkHttp</font></mark>|
      |<font size="3">Jetpack</font>|<mark><font size="2">Navigation</font></mark> <mark><font size="2">Pager</font></mark> <mark><font size="2">ViewModel</font></mark> <mark><font size="2">DataBinding</font></mark> <mark><font size="2">Compose</font></mark>|
      |<font size="3">Image</font>|<mark><font size="2">Glide</font></mark> <mark><font size="2">Coil</font></mark>|
      |<font size="3">Database</font>|<mark><font size="2">Room</font></mark> <mark><font size="2">Realm</font></mark>|
      |<font size="3">DI</font>|<mark><font size="2">Koin</font></mark> <mark><font size="2">Hilt</font></mark>|
      |<font size="3">Testing</font>|<mark><font size="2">Junit</font></mark> <mark><font size="2">Espresso</font></mark> <mark><font size="2">Mockito</font></mark>|
      |<font size="3">Design Tool</font>|<mark><font size="2">Zeplin</font></mark> <mark><font size="2">Figma</font></mark>|
      |<font size="3">VCS</font>|<mark><font size="2">Svn</font></mark> <mark><font size="2">Git</font></mark>|
      |<font size="3">Communication</font>|<mark><font size="2">Jira</font></mark> <mark><font size="2">Slack</font></mark>|
      |<font size="3">Management</font>|<mark><font size="2">Analytics</font></mark> <mark><font size="2">Crashlytics</font></mark> <mark><font size="2">AppsFlyer</font></mark>|        
        
      <br>
  - title: Competency
      layout: text
      content: |
        - first 
        - second
        - third
        - fourth

  - title: Experience
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Danal
        link: https://www.danal.co.kr/
        caption: 2022.03 ~ 현재
        description: |
          **다모음 Android App 개발 담당**
          
          **주요 프로젝트**
           * 다모음
             * 모바일 결제와 포인트 결제, 포인트 충전, 실물 카드 발급 및 관리, 모바일 헌금하기, 바코드 결제 등의 기능을 제공하는 다날 대표 결제 플랫폼

          <br>
          **주요 업무 및 성과**
          * 포인트 충전 시스템 개발
          * 실물 카드 관리 서비스 개발
          * 레거시코드 제거 및 최적화로 가독성 및 개발속도 향상
          * 모듈 분리를 통한 빌드속도 n% 감소 및 유지보수성 향상
            * Single module -> Multi module Migration
            * Clean Architecture / Repository pattern Migration
          * Refactoring을 통한 Boiler plate code 제거 및 성능 향상  
            * rxJava, LiveData -> Coroutine, Flow Migration
            * Kotlin DSL 적용
            * Koin -> Hilt Migration
            * Compose Migration  
            
          * 사용 기술 스택  
            * <mark>Kotlin</mark> <mark>Kotlin DSL</mark> <mark>Retrofit</mark> <mark>Glide</mark> <mark>rxJava</mark> <mark>LiveData</mark> <mark>View/DataBinding</mark> <mark>Jetpack AAC</mark> <mark>Jetpack Compose</mark> <mark>Hilt</mark> <mark>MVVM</mark> <mark>Firebase</mark> <mark>AppsFlyer</mark>
            <br>
      - layout: top-middle
        border: weak
        title: Rainus
        link: https://www.rainusbiz.com/ko/
        caption: 2021.07 ~ 2022.02
        description: |
          **Rainus Player 신규 기능 개발 및 Front-end 개발 담당**  
          
          **주요 프로젝트**
           * Rainus Player
             - Rainus에서 제조한 Android Signage 기기에 광고 컨텐츠 재생 플레이어로 영상, 이미지, 가격표, 기타 컨텐츠 등을 일자, 시간대에 따라 표시    
          
          <br>
          **주요 업무 및 성과**
          * Rainus Player 내 상품 가격태그 표시 기능 개발
            * 가격태그 관련 rating, reviews, advertise 등 컨텐츠 추가 및 제어  
          * Player용 Web Contents 개발 
            * 고객사(CJ/BMW)에서 사용하는 Widget(Front-end) 개발
          * 사용 기술 스택  
            * <mark>Kotlin</mark> <mark>Retrofit</mark> <mark>Glide</mark> <mark>rxJava</mark> <mark>LiveData</mark> <mark>View/DataBinding</mark> <mark>Koin</mark> <mark>MVVM</mark> <mark>Javascript</mark> <mark>Css</mark>  
            <br>
      - layout: top-middle
        border: weak
        title: Bixolon
        link: https://www.bixolon.com/
        caption: 2018.03 ~ 2021.03
        description: |
          **Bixolon Printer(Label, Mobile) 관련 SDK 및 App 개발**  
          
          **주요 프로젝트**
           * Bixolon Label Printer Android Sdk
             * Android Native 환경에서 각종 설정 및 인쇄 컨텐츠 추가 등을 지원하는 Label Printer 제어용 Sdk 
           * ICPay 결제 App
             * 결제 모듈이 장착된 Printer와 함께 사용하는 오프라인 결제 App
           * Bixolon Printer Javascript Sdk
             * Web 환경에서 각종 설정 및 인쇄 컨텐츠 추가 등을 지원하는 Printer 제어용 Sdk
          
          <br>
          **주요 업무 및 성과**
          * Bixolon Label Printer Android SDK 개발 및 유지보수
            * 코어 모듈 리팩토링을 통해 인쇄 및 프린터 설정 기능 개선
          * Mobile printer용 결제 App 3사(KICC, NICE, KS-NET) 통합
            * One Source 관리를 통한 유지보수성 향상 
          * Bixolon Printer Javascript SDK 개발
            * Web 환경에서의 프린터 접근 및 사용성 향상   
            
          * 사용 기술 스택  
            * <mark>Java</mark> <mark>Kotlin</mark> <mark>Retrofit</mark> <mark>Glide</mark> <mark>MVC</mark> <mark>MVP</mark>  
            <br>
      - layout: top-middle
        border: weak
        title: Zin Corp.
        link: https://zin.co.kr/
        caption: 2014.01 ~ 2017.09
        description: |
          **SPC 그룹사 Mobile POS 및 Cunsulting App 개발**  
          
          **주요 프로젝트**
           * SPC Mobile POS 
             - SPC 그룹 파리크라상 브랜드 소속 가맹점에서 사용되는 주문 및 매출 관리 Mobile POS 개발  
           * SPC PB TCR(Total Cunsulting Report)
             - 상권, 상품, 계절 등 여러 지표에 따라 판매량을 분석하고 추천하는 Cunsulting App 개발  
          
          <br>
          **주요 업무 및 성과**
          * SPC Mobile POS Android App 개발 및 개선
            * 주문 내역 리스트 표시 속도 x% 개선
            * Logger 적용으로 디버그 용이성 증가
          * 파리크라상/파스쿠찌 점포 컨설팅 App 개발(관리자/슈퍼바이저 용)
            * Custom View 구현 및 적용으로 사용량 y% 증가  
            
          * 사용 기술 스택  
            * <mark>Java</mark> <mark>log4j</mark> <mark>AChartEngine</mark> <mark>MVC</mark>
            <br>
  - title: In ordinary days
    layout: text
    content: | 
      책상에 앉아서 공부하는 날 외에는 캠핑, 낚시, 당구, 스노우보드, 서핑 등 활동적인 컨텐츠를 즐깁니다. 새로운 무언가에 도전하는것을 좋아하여 여러 분야의 사람들과 함께 스포츠를 즐기고, 배우곤 합니다.  
      또한 사람들을 만나는 것도 좋아해서 여러가지 활동적인 모임 혹은 컨퍼런스에 참석하기도 합니다.  
      평일에는 가급적 책상과 가까이 붙어 있으려 노력하고, Side Project 또는 학습중인 기술에 대한 프로토타입 등을 만드는 등 이해도를 높여가는 시간을 갖습니다.

  - title: Finally
    layout: text
    content: |
      다양한 프로젝트를 개발해오며 Android 개발자로서의 기술 스택 및 경험, 그리고 자질을 쌓아왔습니다. 지금도, 그리고 앞으로도 꾸준히 노력하겠습니다.  
      기입된 프로젝트 외 기타 프로젝트 및 상세 내용은 [프로젝트 상세내역](https://github.com/bcchoi0202/resume) 에서 확인 가능합니다.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
