# Site
repository: bcchoi0202/r
favicon: images/favicon.ico

version: 2

# Personal info
name: 최병철
title: Android Developer
email: bcchoi0202@gmail.com
phone: 010-6411-8658

# Social links
#twitter_username: sproogen
github_username:  bcchoi8658
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: byungchul0202
#linkedin_username: jameswgrant
# pinterest_username:
# youtube_username:

#About Section
about_title: About me
about_profile_image: images/me.jpg
about_content: |
  안녕하세요, 9년차 개발자 최병철입니다. 
  - 빠르고 사용하기 쉬우면서도 사용에 즐거움을 더해주는 경험을 제공하는 UI를 만드는 것을 좋아합니다. 
  - 일관성, 코딩 컨벤션을 지키기 위해 노력합니다. 
  - 사용자 관점을 최우선으로 생각하고 고민합니다.
  - 새로운 기술을 배우고 도입하는 일에 적극적입니다.
  - 재미와 건강, 함께 하는(할 수 있는) 것에 관심이 많습니다.
content:
  - title: Skills
    layout: list
    content:
      - layout: left
        sub_title: Language
        description: |
          Java, Kotlin
      - layout: left
        sub_title: View
        description: |
          View/Databinding, Jetpack AAC, Jetpack Compose
      - layout: left
        sub_title: Stream
        description: |
          rx(Java/Android)/Livedata, Coroutine/Flow
      - layout: left
        sub_title: Architecture
        description: |
          MVC, MVP, MVVM, MVI(~ing)
      - layout: left
        sub_title: DI
        description: |
          Koin, Hilt
      - layout: left
        sub_title: Design
        description: |
          Zeplin, Figma
      - layout: left
        sub_title: SCM
        description: |
          Svn, Git

#  - title: Experience
#    layout: list
#    content:
#      - layout: top-middle
#        border: weak
#        title: Modern Resume Theme
#        link: sproogen.github.io/modern-resume-theme
#        additional_links:
#          - title: sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: https://github.com/sproogen/modern-resume-theme
#        quote: >
#          A modern simple static resume template and theme. Powered by Jekyll and GitHub pages.
#        description: |
#          This is a <mark>Jekyll</mark> theme that I have recently created, in fact it is what this resume has been built with.
#          I decided I wanted to learn how to create a fully open source project and thought that this would be the perfect project to do this with.
#          It has allowed me to share something I have created in a way that will be helpful for lots of people while also learning from this myself.
#      - layout: top-middle
#        title: itsgoingto.be
#        link: www.itsgoingto.be
#        additional_links:
#          - title: sproogen/itsgoingto.be
#            icon: fab fa-github
#            url: https://github.com/sproogen/itsgoingto.be
#        quote: >
#          itsgoingto.be is a simple voting site where a user can ask a question or topic top put to a vote. This question
#          can then be shared with their friends/colleagues to vote on things like 'Where should we go for lunch?'.
#        description: |
#          The API for this site has been build using <mark>Node.js</mark> while the front end is a <mark>React</mark>/<mark>Redux</mark> app.
#          I have used <mark>Docker</mark> to set up a development environment and <mark>Heroku</mark> to deploy and host the site. I have
#          a suite of unit and API tests for the backend and unit tests for the front end.
#          I have been using this project as a way to increase many of my skills and also learn new things, most recently sockets and Node.JS. I have particually
#          enjoyed managing my own project and designing my own architecture and implementing this to a high standard.
#          Feel free to check out the whole project on GitHub to get a feel for how I work [here](https://github.com/sproogen/itsgoingto.be).


  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: (주)다날
        sub_title: Android Developer
        link: https://www.danal.co.kr/
        caption: 2022.03 ~ 현재
        description: |
          Taken
      - layout: left
        border: weak
        title: Rainus
        link: https://www.rainusbiz.com/ko/
        sub_title: Android Developer
        caption: 2021.07 ~ 2022.02
        description: |
          Workin
      - layout: left
        border: weak
        title: (주)Bixolon
        sub_title: Android Developer
        link: https://www.bixolon.com/
        caption: 2018.03 ~ 2021.03
        content: |
          * Bixolon Label Printer SDK 개발
          * Bixolon Label Printer SDK 개발
          * Bixolon Label Printer SDK 개발
      - layout: left
        border: weak
        title: (주)진코퍼레이션
        sub_title: Android Development
        link: http://zin.co.kr/
        caption: 2014.01 ~ 2017.09
        description: |
          I was asked

  - title: Education
    layout: list
    content:
      - title: Bristol University
        sub_title: BSc Computer Science
        caption: 2010 - 2013
        description: |
          During my degree at Bristol University I learnt lots of key skills such as team work and project management. Although
          we mainly focused on software development and the principles of programming I use a lot of these skills to
          my advantage in my day to day work.
          While at Bristol Uni I spent a lot of my free time with the Kitesurfing society. I spent 3 years on the committee
          as a secretary, trip rep and then media and promotions manager. During this time I took on roles from organising
          transport and designing posters to organising a trip to Portugal for over 30 students.
  - title: When I'm Not Programming
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not sat at my desk I am very active and spend most of my time outdoors. I do a lot a sports such as
      mountain biking, road cycling, kitesuring and horse riding as well as trying to make time for things like
      rock climbing and playing some rugby. I currently have 2 horses and find this is a great way to get out of the house
      and taking my mind of things while learing to showjump.
      I'm interested in photography and videography as I like to be creative, this is mainly through sport but
      I enjoy landscape and abstract photography too. I like to showcase my work on instagram if
      you would like to take a look - [jameswgrant](https://www.instagram.com/jameswgrant/).
      Finally during the rest of my free time you will either find me working on my bikes, rock climbing at one of
      Bristol's indoor climbing centres or down 'The Rec' supporting Bath Rugby.
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
